### ISSUE TITLE
Call to an undefined method CodeIgniter\HTTP\CLIRequest|CodeIgniter\HTTP\IncomingRequest::isHtmx(). 

### ISSUE THREAD

**Issue by jozefrebjak** [michalsn/codeigniter-htmx#2]
@michalsn Thank you for a perfect library. I'm just exploring what is possible to do with HTMX, till the library exists I used `$this->requst->isAjax()`  method with Ajax-Header htmx extension. 

Now I installed this library and changed `isAjax()` to `isHtmx()`. It works as excepted, but now PHPStan is reporting issue with:

```sh
Call to an undefined method CodeIgniter\HTTP\CLIRequest|CodeIgniter\HTTP\IncomingRequest::isHtmx().  
```

So for now I'm just ignoring this error with `ignore-next-line` PHPDoc.

Psalm is reporting this issue with:

```sh
ERROR: UndefinedMethod - modules/Recycler/Controllers/RecycleController.php:59:29 - Method CodeIgniter\HTTP\CLIRequest::isHtmx does not exist (see https://psalm.dev/022)
```

This error is reported, because in BaseController is defined default:

```php
use CodeIgniter\HTTP\IncomingRequest;
```

for 

```php
    /**
     * Instance of the main Request object.
     *
     * @var CLIRequest|IncomingRequest
     */
    protected $request;
```

So, easy solution is to change default IncomingRequst for:

```php
use Michalsn\CodeIgniterHtmx\HTTP\IncomingRequest;
```

or suggest users to use some other variable than `$request` to use with all of defined functions in README. 

@michalsn  What you think ?

**Comment by michalsn** [comment]
Thanks for reporting. I will look into it.

**Comment by michalsn** [comment]
@jozefrebjak Thanks!

I added the Troubleshooting section at the end of the README. Hopefully, it will help others to deal with these types of problems.
