### ISSUE TITLE
Debug toolbar integration

### ISSUE THREAD

**Issue by jonsmith1982** [michalsn/codeigniter-htmx#25]
Not really an issue but how about just advising users to include the HTMX Ajax-header extension and set hx-ext=“ajax-header” to body tag then you don’t have to change Toolbar::prepare and create a services::Toolbar function to make it work as it is supposed to?

**Comment by michalsn** [comment]
Of course, in theory, you can definitely do it with the mentioned extension, but the reason to do it the way it is done now was to differentiate an AJAX request from an HTMX request. 

In the variant proposed by you, `$this->request->isAJAX()` would return `true` every time even for an HTMX request. And that was something I was hoping to avoid.
