### ISSUE TITLE
bug: Saving the previous URL

### ISSUE THREAD

**Issue by neznaika0** [michalsn/codeigniter-htmx#81]
Otherwise, the HTMX request may change the previous URL. While we are updating on the same page (tab), there is no problem. But if `previous_url() `returns another page, the result is unexpected.
File **[vendor/codeigniter4/framework/system/CodeIgniter.php](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/CodeIgniter.php)** in `storePreviousURL()`:
```php
// Ignore AJAX requests
// Possible solution
// if ((method_exists($this->request, 'isHTMX') && $this->request->isHTMX()) || (method_exists($this->request, 'isAJAX') && $this->request->isAJAX())) {
if (method_exists($this->request, 'isAJAX') && $this->request->isAJAX()) {
    return;
}
...
```
or identify HTMX = AJAX. But it can introduce new dependencies.

**Comment by michalsn** [comment]
Well, I don't think there is currently anything that can be done about it. Adding customization options for this would be problematic.

The only workaround would be to use the [ajax-header](https://github.com/bigskysoftware/htmx-extensions/blob/main/src/ajax-header/README.md) extension.

**Comment by neznaika0** [comment]
the sick option is to change the `service('codeigniter')`. 

Perhaps it is worth writing recommendations?
https://github.com/michalsn/codeigniter-htmx/blob/develop/docs/troubleshooting.md

**Comment by michalsn** [comment]
Oh, I forgot that CodeIgnter class is also a service. In that case, feel free to send a pull request.
